# Generated by Django 3.2.20 on 2023-07-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pharma', '0003_auto_20230725_2043'),
        ('ProductManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pharma.pharma'),
        ),
    ]
