# Generated by Django 3.2.20 on 2023-07-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_permissions',
        ),
    ]
