# Generated by Django 3.2.20 on 2023-07-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0004_auto_20230719_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_type',
            field=models.CharField(default='patient', max_length=10),
        ),
    ]
