# Generated by Django 3.2.20 on 2023-07-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_pharma', to='auth.group')),
                ('user_permissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions_pharma', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
