# Generated by Django 3.2.20 on 2023-07-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharma',
            name='is_pharma',
            field=models.BooleanField(default=True),
        ),
    ]
